# Generated by Django 4.2.11 on 2024-03-25 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smartsole_gaittest", "0003_alter_gaittest_end_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gaittest",
            options={},
        ),
    ]
