# Generated by Django 4.2.11 on 2024-03-26 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smartsole_gaittest", "0004_alter_gaittest_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="gaittest",
            table="smartsole_gaittest",
        ),
    ]
