# Generated by Django 4.2.11 on 2024-03-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartsole_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="height",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="shoe_size",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="weight",
            field=models.FloatField(null=True),
        ),
    ]
