# Generated by Django 4.2.11 on 2024-03-25 11:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("smartsole_gaittest", "0003_alter_gaittest_end_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("sensor_id", models.IntegerField()),
                ("force", models.FloatField()),
                ("timestamp", models.DateTimeField()),
                ("step_number", models.IntegerField()),
                (
                    "gaittest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="smartsole_gaittest.gaittest",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
