# Generated by Django 4.2.11 on 2024-03-26 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("smartsole_sensor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sensor",
            table="smartsole_sensor",
        ),
    ]
