# Generated by Django 4.2.11 on 2024-03-13 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bleapp", "0004_remove_profile_first_name_remove_profile_last_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensorreading",
            old_name="test_id",
            new_name="step_id",
        ),
        migrations.RenameField(
            model_name="test",
            old_name="user_id",
            new_name="profile_id",
        ),
        migrations.CreateModel(
            name="AverageStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_0_time", models.IntegerField()),
                ("sensor_0_value", models.FloatField()),
                ("sensor_1_time", models.IntegerField()),
                ("sensor_1_value", models.FloatField()),
                ("sensor_2_time", models.IntegerField()),
                ("sensor_2_value", models.FloatField()),
                ("sensor_3_time", models.IntegerField()),
                ("sensor_3_value", models.FloatField()),
                ("sensor_4_time", models.IntegerField()),
                ("sensor_4_value", models.FloatField()),
                ("sensor_5_time", models.IntegerField()),
                ("sensor_5_value", models.FloatField()),
                (
                    "test_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bleapp.test"
                    ),
                ),
            ],
        ),
    ]
