# Generated by Django 4.1.1 on 2024-03-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bleapp", "0005_rename_test_id_sensorreading_step_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="foot_length",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="foot_width",
        ),
        migrations.RemoveField(
            model_name="test",
            name="end_time",
        ),
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="height",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="shoe_size",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bleapp.user",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="weight",
            field=models.FloatField(null=True),
        ),
    ]
