# Generated by Django 4.2.3 on 2024-03-13 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("bleapp", "0007_alter_test_name_alter_test_start_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="age",
        ),
        migrations.AddField(
            model_name="profile",
            name="dob",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="shoe_size",
            field=models.FloatField(null=True),
        ),
    ]
