# Generated by Django 4.2.3 on 2024-03-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bleapp", "0010_alter_test_unique_together_alter_test_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
