# Generated by Django 4.1.1 on 2024-03-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bleapp", "0013_remove_averagesensorreading_value_remove_profile_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.IntegerField(default=0),
        ),
    ]
