# Generated by Django 4.1.1 on 2024-03-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bleapp", "0014_profile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="test",
            name="duration",
        ),
        migrations.AddField(
            model_name="test",
            name="end_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
